-- ChargeFind seed stations. Run after schema.sql:
-- psql -h 127.0.0.1 -U chargefind -d chargefind -f db/seed.sql

INSERT INTO stations
  (id, name, address, distance_km, latitude, longitude, price_per_kwh,
   charger_types, connectors,
   power_kw, total_slots, operating_start_hour, operating_end_hour,
   amenities, is_offline)
VALUES
  ('tata-hub', 'Tata Power Charging Hub',
   'Plot 42, MIDC Industrial Area, Andheri East, Mumbai 400093',
   2.4, 19.1102, 72.8658, 18, '{DC Fast}', '{CCS2,CHAdeMO}',
   '{"DC Fast": 60}', 8, 6, 22,
   '{Café,Restrooms,Wi-Fi,Covered Parking,CCTV}', FALSE),
  ('jiobp-pulse', 'Jio-bp Pulse',
   'Ground Floor, Cyber Towers, HITEC City, Hyderabad 500081',
   3.1, 17.4435, 78.3772, 16, '{AC,DC Fast}', '{Type 2,CCS2}',
   '{"AC": 22, "DC Fast": 60}', 12, 0, 24,
   '{Food Court,Lounge,Wi-Fi,Restrooms,Car Wash}', FALSE),
  ('chargezone-express', 'ChargeZone Express',
   'NH-48 Service Lane, Gurugram, Haryana 122001',
   4.8, 28.4600, 76.9100, 22, '{DC Ultra Fast}', '{CCS2}',
   '{"DC Ultra Fast": 120}', 6, 6, 23,
   '{Coffee Kiosk,Restrooms,Highway Access}', FALSE),
  ('statiq-point', 'Statiq Neighborhood Point',
   '14, Green Park Extension, New Delhi 110016',
   1.2, 28.5577, 77.2067, 14, '{AC}', '{Type 2}',
   '{"AC": 11}', 4, 8, 20,
   '{Residents Parking}', FALSE),
  ('goego-depot', 'goEgo Depot (Maintenance)',
   'Survey 88, Baner Road, Pune 411045',
   6.5, 18.5679, 73.7700, 15, '{DC Fast}', '{CCS2,CHAdeMO}',
   '{"DC Fast": 50}', 10, 6, 22,
   '{Service Bay}', TRUE)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  distance_km = EXCLUDED.distance_km,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  price_per_kwh = EXCLUDED.price_per_kwh,
  charger_types = EXCLUDED.charger_types,
  connectors = EXCLUDED.connectors,
  power_kw = EXCLUDED.power_kw,
  total_slots = EXCLUDED.total_slots,
  operating_start_hour = EXCLUDED.operating_start_hour,
  operating_end_hour = EXCLUDED.operating_end_hour,
  amenities = EXCLUDED.amenities,
  is_offline = EXCLUDED.is_offline;

INSERT INTO stations
  (id, name, address, distance_km, latitude, longitude, price_per_kwh,
   charger_types, connectors,
   power_kw, total_slots, operating_start_hour, operating_end_hour,
   amenities, is_offline)
VALUES
  ('voltway-highway', 'VoltWay Highway Hub',
   'Km 42, NH-48 Delhi-Jaipur Highway, Haryana 122001',
   8.7, 27.8800, 76.2900, 24, '{DC Fast,DC Ultra Fast}', '{CCS2}',
   '{"DC Fast": 60, "DC Ultra Fast": 150}', 16, 0, 24,
   '{Highway Access,Food Court,Restrooms,Wi-Fi}', FALSE),
  ('mallcharge-bank', 'MallCharge Basement Bank',
   'B2 Parking, Inorbit Mall, Whitefield, Bengaluru 560066',
   5.2, 12.9698, 77.7499, 12, '{AC}', '{Type 2}',
   '{"AC": 7.4}', 20, 10, 22,
   '{Mall Access,Food Court,CCTV}', FALSE),
  ('ecocharge-solar', 'EcoCharge Solar Park',
   'Plot 7, Solar Park Road, Charanka, Gujarat 385001',
   7.9, 23.9040, 72.1970, 17, '{DC Fast}', '{CCS2}',
   '{"DC Fast": 60}', 6, 6, 20,
   '{Solar Powered,Café,Garden}', FALSE),
  ('budgetvolt-depot', 'BudgetVolt Depot',
   'Gala 12, MIDC Bhosari, Pune 411026',
   9.6, 18.6250, 73.8360, 11, '{DC Fast}', '{CCS2,CHAdeMO}',
   '{"DC Fast": 50}', 10, 0, 24,
   '{Parking,Tea Stall}', FALSE),
  ('heritage-chademo', 'Heritage CHAdeMO Point',
   '3, Museum Road, Bengaluru 560025',
   3.8, 12.9757, 77.6013, 13, '{DC Fast}', '{CHAdeMO}',
   '{"DC Fast": 50}', 4, 9, 21,
   '{Kiosk}', FALSE),
  ('cityone-mega', 'CityOne Mega Hub',
   'Tower A, Cyber City, Gurugram, Haryana 122002',
   6.1, 28.4949, 77.0885, 20, '{AC,DC Fast,DC Ultra Fast}', '{Type 2,CCS2,CHAdeMO}',
   '{"AC": 22, "DC Fast": 60, "DC Ultra Fast": 120}', 24, 0, 24,
   '{Lounge,Food Court,Wi-Fi,Restrooms,Car Wash}', FALSE)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  distance_km = EXCLUDED.distance_km,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  price_per_kwh = EXCLUDED.price_per_kwh,
  charger_types = EXCLUDED.charger_types,
  connectors = EXCLUDED.connectors,
  power_kw = EXCLUDED.power_kw,
  total_slots = EXCLUDED.total_slots,
  operating_start_hour = EXCLUDED.operating_start_hour,
  operating_end_hour = EXCLUDED.operating_end_hour,
  amenities = EXCLUDED.amenities,
  is_offline = EXCLUDED.is_offline;
